import type { INodeProperties } from 'n8n-workflow';
import { forV2, projectLocator } from './common';

export const mediaOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: forV2('media'),
	default: 'upload',
	options: [
		{
			name: 'Delete',
			value: 'delete',
			description: 'Delete a media object that is not attached to an item',
			action: 'Delete media',
		},
		{
			name: 'Download',
			value: 'download',
			description: 'Download a media object as binary data',
			action: 'Download media',
		},
		{ name: 'Get', value: 'get', description: 'Get a media object’s details', action: 'Get media' },
		{
			name: 'Get Many',
			value: 'getAll',
			description: 'Get many media objects in a project',
			action: 'Get many media',
		},
		{
			name: 'Get Usage',
			value: 'getUsage',
			description: 'Get a project’s storage use and limit',
			action: 'Get media usage',
		},
		{
			name: 'Import From URL',
			value: 'importFromUrl',
			description: 'Have SwipeFlow fetch a file from a URL',
			action: 'Import media from a URL',
		},
		{ name: 'Upload', value: 'upload', description: 'Upload binary data', action: 'Upload media' },
	],
};

export const mediaProperties: INodeProperties[] = [
	projectLocator('media', ['getAll', 'getUsage', 'importFromUrl', 'upload']),
	{
		displayName: 'Media ID',
		name: 'mediaId',
		type: 'string',
		required: true,
		default: '',
		description: 'The ID of the media object',
		displayOptions: forV2('media', ['delete', 'download', 'get']),
	},
	{
		displayName: 'Input Binary Field',
		name: 'binaryPropertyName',
		type: 'string',
		required: true,
		default: 'data',
		hint: 'The name of the input binary field containing the file to upload',
		displayOptions: forV2('media', ['upload']),
	},
	{
		displayName: 'File Name',
		name: 'fileName',
		type: 'string',
		default: '',
		description: 'Overrides the name of the binary file',
		displayOptions: forV2('media', ['upload']),
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'https://example.com/image.png',
		description: 'A publicly reachable https URL',
		displayOptions: forV2('media', ['importFromUrl']),
	},
	{
		displayName: 'File Name',
		name: 'fileName',
		type: 'string',
		default: '',
		description: 'Name to store the file under. Defaults to the name in the URL.',
		displayOptions: forV2('media', ['importFromUrl']),
	},
	{
		displayName: 'Put Output in Field',
		name: 'binaryPropertyName',
		type: 'string',
		required: true,
		default: 'data',
		hint: 'The name of the output binary field to put the file in',
		displayOptions: forV2('media', ['download']),
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: forV2('media', ['getAll']),
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: forV2('media', ['getAll'], { returnAll: [false] }),
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: forV2('media', ['getAll']),
		options: [
			{
				displayName: 'Attached',
				name: 'attached',
				type: 'boolean',
				default: true,
				description:
					'Whether to return only media that is (true) or is not (false) attached to an item',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: 'uploaded',
				options: [
					{ name: 'Delete Pending', value: 'delete_pending' },
					{ name: 'Deleted', value: 'deleted' },
					{ name: 'Import Pending', value: 'import_pending' },
					{ name: 'Upload Pending', value: 'upload_pending' },
					{ name: 'Uploaded', value: 'uploaded' },
				],
			},
		],
	},
];
