import type { INodeProperties } from 'n8n-workflow';
import { forV2, projectLocator } from './common';

export const WEBHOOK_EVENT_OPTIONS: INodeProperties['options'] = [
	{ name: 'Item Approved', value: 'item.approved' },
	{ name: 'Item Change Requested', value: 'item.change_requested' },
	{ name: 'Item Created', value: 'item.created' },
	{ name: 'Item Deleted', value: 'item.deleted' },
	{ name: 'Item Processed', value: 'item.processed' },
	{ name: 'Item Rejected', value: 'item.rejected' },
	{ name: 'Item Updated', value: 'item.updated' },
	{ name: 'Project Triggered', value: 'project.trigger' },
];

export const webhookOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: forV2('webhook'),
	default: 'getAll',
	options: [
		{
			name: 'Create',
			value: 'create',
			description: 'Register a webhook on a project',
			action: 'Create a webhook',
		},
		{
			name: 'Delete',
			value: 'delete',
			description: 'Delete a webhook',
			action: 'Delete a webhook',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			description: 'Get the webhooks of a project',
			action: 'Get many webhooks',
		},
		{
			name: 'Send Test',
			value: 'test',
			description: 'Send a test event to a webhook',
			action: 'Send a test event to a webhook',
		},
	],
};

export const webhookProperties: INodeProperties[] = [
	projectLocator('webhook', ['create', 'delete', 'getAll', 'test']),
	{
		displayName: 'Webhook ID',
		name: 'webhookId',
		type: 'string',
		required: true,
		default: '',
		description: 'The ID of the webhook',
		displayOptions: forV2('webhook', ['delete', 'test']),
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'https://example.com/webhook',
		description: 'Where SwipeFlow sends events',
		displayOptions: forV2('webhook', ['create']),
	},
	{
		displayName: 'Events',
		name: 'events',
		type: 'multiOptions',
		required: true,
		default: ['item.approved', 'item.rejected'],
		options: WEBHOOK_EVENT_OPTIONS,
		description: 'Which events to send',
		displayOptions: forV2('webhook', ['create']),
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: forV2('webhook', ['create']),
		options: [
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'A label shown in SwipeFlow',
			},
			{
				displayName: 'Signing Secret',
				name: 'secret',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				description:
					'Used to sign deliveries so the receiver can verify them. Generated by SwipeFlow if left empty.',
			},
		],
	},
];
