#!/usr/bin/env node
// Vendors the type-only surface of @swipeflow/sdk into nodes/SwipeFlow/sdk.
// The published node must have no runtime dependencies, so it cannot import the
// SDK package (which pulls in axios). Models and media helpers are copied verbatim;
// the request layer in sdk/client.ts is hand-written on top of n8n's HTTP helpers.
//
//   node scripts/sync-sdk.mjs [path-to-swipeflow-sdk-ts]
import {
	cpSync,
	existsSync,
	mkdirSync,
	readFileSync,
	readdirSync,
	rmSync,
	writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sdkRoot = resolve(process.argv[2] ?? join(root, '../../sdk/swipeflow-sdk-ts'));
const target = join(root, 'nodes/SwipeFlow/sdk');

if (!existsSync(join(sdkRoot, 'src/generated/models'))) {
	console.error(`Not a swipeflow-sdk-ts checkout: ${sdkRoot}`);
	process.exit(1);
}

const version = JSON.parse(readFileSync(join(sdkRoot, 'package.json'), 'utf8')).version;
const commit = execFileSync('git', ['-C', sdkRoot, 'rev-parse', '--short', 'HEAD'], {
	encoding: 'utf8',
}).trim();

rmSync(join(target, 'models'), { recursive: true, force: true });
mkdirSync(join(target, 'models'), { recursive: true });
cpSync(join(sdkRoot, 'src/generated/models'), join(target, 'models'), { recursive: true });

// The generated files carry a blanket `eslint-disable`. The stock lint config (enforced by
// `n8n.strict`) reports it as unused in files that need no suppression, so keep it only
// where the generator's namespaces or `any` would otherwise fail lint.
for (const name of readdirSync(join(target, 'models'))) {
	const file = join(target, 'models', name);
	const source = readFileSync(file, 'utf8');
	const code = source.replace(/\/\*[\s\S]*?\*\//g, '');
	if (!/\bnamespace\b|\bany\b/.test(code)) {
		writeFileSync(file, source.replace('/* eslint-disable */\n', ''));
	}
}
cpSync(join(sdkRoot, 'src/media.ts'), join(target, 'media.ts'));

const modelExports = readFileSync(join(sdkRoot, 'src/generated/index.ts'), 'utf8')
	.split('\n')
	.filter((line) => line.startsWith('export') && line.includes("'./models/"));

writeFileSync(
	join(target, 'models.ts'),
	['/* Generated by scripts/sync-sdk.mjs — do not edit. */', ...modelExports, ''].join('\n'),
);

writeFileSync(
	join(target, 'VENDORED.md'),
	[
		'# Vendored SwipeFlow SDK',
		'',
		`Source: \`@swipeflow/sdk\` ${version} (swipeflow-sdk-ts @ ${commit})`,
		'',
		'Copied by `scripts/sync-sdk.mjs`: `models/`, `models.ts` and `media.ts`. Do not edit them by hand;',
		'refresh with `npm run sync-sdk` after the SDK is regenerated.',
		'',
		'`client.ts` and `index.ts` are hand-written for this package.',
		'',
	].join('\n'),
);

console.log(
	`Vendored @swipeflow/sdk ${version} @ ${commit}: ${readdirSync(join(target, 'models')).length} models`,
);
